[package]
name = "wasi-cap-std-sync"
version = "0.29.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
include = ["src/**/*", "README.md", "LICENSE" ]

[dependencies]
wasi-common = { path = "../", version = "0.29.0" }
async-trait = "0.1"
anyhow = "1.0"
cap-std = "0.19.0"
cap-fs-ext = "0.19.0"
cap-time-ext = "0.19.0"
cap-rand = "0.19.0"
fs-set-times = "0.11.0"
system-interface = { version = "0.14.0", features = ["cap_std_impls"] }
tracing = "0.1.19"
bitflags = "1.2"
io-lifetimes = { version = "0.3.0", default-features = false }

[target.'cfg(unix)'.dependencies]
rsix = "0.22.4"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
lazy_static = "1.4"

[dev-dependencies]
tempfile = "3.1.0"
