[package]
name = "winx"
version = "0.12.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
description = "Windows API helper library"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"

[dependencies]
bitflags = "1.0"
cvt = "0.1"

[dependencies.winapi]
version = "^0.3"
features = [
    "std",
    "errhandlingapi",
    "handleapi",
    "processthreadsapi",
    "profileapi",
    "securitybaseapi",
    "winbase",
    "winerror",
    "ws2def",
    "fileapi",
    "aclapi",
]

[badges]
maintenance = { status = "actively-developed" }
