[package]
name = "isle"
version = "0.1.0"
authors = ["Chris Fallin <chris@cfallin.org>", "Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
log = "0.4"
miette = "3.0.0"
thiserror = "1.0.29"
