[package]
authors = ["The Wasmtime Project Developers"]
description = "Fuzzing infrastructure for Wasmtime"
edition = "2018"
name = "wasmtime-fuzzing"
publish = false
version = "0.19.0"

[dependencies]
anyhow = "1.0.22"
arbitrary = { version = "0.4.1", features = ["derive"] }
env_logger = "0.7.1"
log = "0.4.8"
rayon = "1.2.1"
wasmparser = "0.63.0"
wasmprinter = "0.2.10"
wasmtime = { path = "../wasmtime" }
wasmtime-wast = { path = "../wast" }
wasm-smith = "0.1.9"

[dev-dependencies]
wat = "1.0.23"
