[package]
authors = ["The Wasmtime Project Developers"]
description = "Fuzzing infrastructure for Wasmtime"
edition = "2018"
name = "wasmtime-fuzzing"
publish = false
version = "0.9.0"

[dependencies]
anyhow = "1.0.22"
arbitrary = { version = "0.3.2", features = ["derive"] }
binaryen = "0.10.0"
env_logger = "0.7.1"
log = "0.4.8"
wasmparser = "0.51.0"
wasmprinter = "0.2.0"
wasmtime = { path = "../api", version = "0.9.0" }

[dev-dependencies]
wat = "1.0"
