[package]
name = "wasmstandalone_tools"
authors = ["The Cretonne Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmstandalone crate"
license = "MIT/Apache-2.0"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/sunfishcode/wasmstandalone"
publish = false

[[bin]]
name = "wasmstandalone"
path = "src/main.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cretonne = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-frontend = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-reader = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-wasm = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-native = { git = "https://github.com/stoklund/cretonne.git" }
wasmstandalone_runtime = { path = "lib/runtime" }
wasmstandalone_execute = { path = "lib/execute" }
wasmstandalone_obj = { path = "lib/obj" }
docopt = "0.8.3"
serde = "1.0.27"
serde_derive = "1.0.27"
tempdir = "*"
faerie = { git = "https://github.com/m4b/faerie" }

[workspace]
