[package]
name = "wasmstandalone_tools"
authors = ["The Cretonne Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmstandalone crate"
license = "MIT/Apache-2.0"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/sunfishcode/wasmstandalone"
publish = false

[[bin]]
name = "wasmstandalone"
path = "src/main.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cretonne-codegen = "0.9.0"
cretonne-frontend = "0.9.0"
cretonne-reader = "0.9.0"
cretonne-wasm = "0.9.0"
cretonne-native = "0.9.0"
wasmstandalone_runtime = { path = "lib/runtime" }
wasmstandalone_execute = { path = "lib/execute" }
wasmstandalone_obj = { path = "lib/obj" }
docopt = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
tempdir = "*"
faerie = "0.4.1"

[workspace]
