[package]
name = "wiggle"
version = "0.1.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkonk@jakubkonka.com>"]
edition = "2018"

[dependencies]
wiggle-generate = { path = "crates/generate" }
wiggle-runtime = { path = "crates/runtime" }

[dev-dependencies]
wiggle-test = { path = "crates/test" }
proptest = "0.9"

[workspace]
members = [
  "crates/generate",
  "crates/runtime",
  "crates/test",
]
exclude = ["crates/WASI"]
