[package]
name = "wasi-common"
version = "0.1.0"
authors = [
    "Adam C. Foltzer <acfoltzer@fastly.com>",
    "Frank Denis <github@pureftpd.org>",
    "Jakub Konka <kubkon@jakubkonka.com>",
    "Dan Gohman <sunfish@mozilla.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
wasi-common-cbindgen = { path = "wasi-common-cbindgen" }
failure = "0.1"
libc = "0.2"
rand = "0.6"
cfg-if = "0.1.9"
log = "0.4"

[target.'cfg(unix)'.dependencies]
nix = "0.13"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features=["std", "handleapi", "processthreadsapi", "winbase", "ws2def", "fileapi"] }

[dev-dependencies]
wasmtime-runtime = { git = "https://github.com/cranestation/wasmtime" }
wasmtime-environ = { git = "https://github.com/cranestation/wasmtime" }
wasmtime-jit = { git = "https://github.com/cranestation/wasmtime" }
cranelift-codegen = "0.30.0"
cranelift-entity = "0.30.0"
cranelift-wasm = "0.30.0"
cranelift-native = "0.30.0"
target-lexicon = "0.3.0"
pretty_env_logger = "0.3"

[lib]
name = "wasi_common"
crate-type = ["rlib", "staticlib", "cdylib"]

[workspace]
