[package]
name = "wasi-common"
version = "0.1.0"
authors = [
    "Adam C. Foltzer <acfoltzer@fastly.com>",
    "Frank Denis <github@pureftpd.org>",
    "Jakub Konka <kubkon@jakubkonka.com>",
    "Dan Gohman <sunfish@mozilla.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
cast = "0.2"
failure = "0.1"
libc = "0.2"
nix = "0.13"
rand = "0.6"

[lib]
name = "wasi_common"
crate-type = ["rlib", "staticlib", "cdylib"]
