[package]
name = "wasi-common"
version = "0.5.0"
authors = [
    "Adam C. Foltzer <acfoltzer@fastly.com>",
    "Frank Denis <github@pureftpd.org>",
    "Jakub Konka <kubkon@jakubkonka.com>",
    "Dan Gohman <sunfish@mozilla.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "WASI implementation in Rust"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/wasi-common"
readme = "README.md"

[features]
# this feature requires wasm32-wasi target installed, and it enables wasm32
# integration tests when run with `cargo test --features wasm_tests`
wasm_tests = []

[dependencies]
wasi-common-cbindgen = { path = "wasi-common-cbindgen", version = "0.5.0" }
failure = "0.1"
libc = "0.2"
rand = "0.7"
cfg-if = "0.1.9"
log = "0.4"
filetime = "0.2.7"
lazy_static = "1.4.0"
num = { version = "0.2.0", default-features = false }
wig = { path = "wig", version = "0.1.0" }

[target.'cfg(unix)'.dependencies]
nix = "0.15"

[target.'cfg(windows)'.dependencies]
winx = { path = "winx", version = "0.5.0" }
winapi = "0.3"
cpu-time = "1.0"


[dev-dependencies]
wasmtime-runtime = { git = "https://github.com/acfoltzer/wasmtime", rev = "d99e2fb" }
wasmtime-environ = { git = "https://github.com/acfoltzer/wasmtime", rev = "d99e2fb" }
wasmtime-jit = { git = "https://github.com/acfoltzer/wasmtime", rev = "d99e2fb" }
wasmtime-wasi = { git = "https://github.com/acfoltzer/wasmtime", rev = "d99e2fb" }
wasmtime-api = { git = "https://github.com/acfoltzer/wasmtime", rev = "d99e2fb" }
cranelift-codegen = "0.47.0"
target-lexicon = "0.8.1"
pretty_env_logger = "0.3.0"
tempfile = "3.1.0"
# this is just a temp fix to make the tests build and run; I hope this to be
# completely removed when we merge `wasi-common` into `wasmtime`
faerie = "=0.11.0"

[patch."https://github.com/CraneStation/wasi-common"]
wasi-common = { path = "." }

[build-dependencies]
cfg-if = "0.1.9"

[lib]
name = "wasi_common"
crate-type = ["rlib", "staticlib", "cdylib"]

[workspace]
members = ["wasi-common-cbindgen"]
exclude = ["winx", "misc_testsuite"]
