[package]
name = "wasmtime-cli"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
description = "Command-line interface for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://bytecodealliance.github.io/wasmtime/cli.html"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
default-run = "wasmtime"
publish = false

[lib]
doctest = false

[[bin]]
name = "wasmtime"
path = "src/bin/wasmtime.rs"
doc = false

[dependencies]
# Enable all supported architectures by default.
wasmtime = { path = "crates/api", default-features = false }
wasmtime-debug = { path = "crates/debug" }
wasmtime-environ = { path = "crates/environ" }
wasmtime-jit = { path = "crates/jit" }
wasmtime-obj = { path = "crates/obj" }
wasmtime-wast = { path = "crates/wast" }
wasmtime-wasi = { path = "crates/wasi" }
wasi-common = { path = "crates/wasi-common" }
structopt = { version = "0.3.5", features = ["color", "suggestions"] }
faerie = "0.15.0"
anyhow = "1.0.19"
target-lexicon = { version = "0.10.0", default-features = false }
pretty_env_logger = "0.4.0"
file-per-thread-logger = "0.1.1"
wat = "1.0.10"
libc = "0.2.60"
rayon = "1.2.1"

[dev-dependencies]
wasmtime-runtime = { path = "crates/runtime" }
more-asserts = "0.2.1"
# This feature requires the wasm32-wasi target be installed. It enables
# wasm32-wasi integration tests. To enable, run
# `cargo test --features test-programs`.
test-programs = { path = "crates/test-programs" }
tempfile = "3.1.0"
filecheck = "0.5.0"

[build-dependencies]
anyhow = "1.0.19"

[profile.release.build-override]
opt-level = 0

[workspace]
members = [
  "cranelift",
  "crates/c-api",
  "crates/fuzzing",
  "crates/misc/py",
  "crates/misc/run-examples",
  "crates/misc/rust",
  "crates/wiggle",
  "examples/fib-debug/wasm",
  "examples/wasi/wasm",
  "fuzz",
]

[features]
default = ["jitdump", "wasmtime/wat"]
lightbeam = [
    "wasmtime-environ/lightbeam",
    "wasmtime-jit/lightbeam",
    "wasmtime-wast/lightbeam",
    "wasmtime/lightbeam",
]
jitdump = ["wasmtime/jitdump"]
test_programs = ["test-programs/test_programs"]

[badges]
maintenance = { status = "actively-developed" }
