[package]
name = "wasmtime-tools"
authors = ["The Wasmtime Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmtime crate"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
categories = ["wasm"]
repository = "https://github.com/CraneStation/wasmtime"
publish = false

[[bin]]
name = "wasmtime"
path = "src/main.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cranelift-codegen = "0.24.0"
cranelift-native = "0.24.0"
cranelift-entity = "0.24.0"
cranelift-wasm = "0.24.0"
wasmtime-environ = { path = "lib/environ" }
wasmtime-execute = { path = "lib/execute" }
wasmtime-obj = { path = "lib/obj" }
docopt = "1.0.1"
serde = "1.0.75"
serde_derive = "1.0.75"
tempdir = "*"
faerie = "0.6.0"
target-lexicon = { version = "0.2.0", default-features = false }

[workspace]
