[package]
name = "wasmtime"
authors = ["The Wasmtime Project Developers"]
version = "0.2.0"
description = "Command-line interface for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
categories = ["wasm"]
repository = "https://github.com/CraneStation/wasmtime"
edition = "2018"
default-run = "wasmtime"

[dependencies]
cranelift-codegen = { version = "0.43.1", features = ["enable-serde"] }
cranelift-entity = { version = "0.43.1", features = ["enable-serde"] }
cranelift-wasm = { version = "0.43.1", features = ["enable-serde"] }
cranelift-native = "0.43.1"
wasmtime-api = { path = "wasmtime-api" }
wasmtime-debug = { path = "wasmtime-debug" }
wasmtime-environ = { path = "wasmtime-environ" }
wasmtime-interface-types = { path = "wasmtime-interface-types" }
wasmtime-runtime = { path = "wasmtime-runtime" }
wasmtime-jit = { path = "wasmtime-jit" }
wasmtime-obj = { path = "wasmtime-obj" }
wasmtime-wast = { path = "wasmtime-wast" }
wasmtime-wasi = { path = "wasmtime-wasi" }
wasmtime-wasi-c = { path = "wasmtime-wasi-c", optional = true }
wasi-common = { git = "https://github.com/CraneStation/wasi-common", rev = "8ea7a983d8b1364e5f62d2adf0e74b3b8db1c9b3"}
docopt = "1.0.1"
serde = { "version" = "1.0.94", features = ["derive"] }
faerie = "0.11.0"
failure = "0.1"
target-lexicon = { version = "0.8.1", default-features = false }
pretty_env_logger = "0.3.0"
file-per-thread-logger = "0.1.1"
wabt = "0.9"
libc = "0.2.60"
errno = "0.2.4"
rayon = "1.1"
wasm-webidl-bindings = "0.4"

# build.rs tests whether to enable a workaround for the libc strtof function.
[target.'cfg(target_os = "linux")'.build-dependencies]
libc = "0.2.60"

[workspace]
members = [
  "misc/wasmtime-rust",
  "misc/wasmtime-py",
]

[features]
# Enable all supported architectures by default.
default = ["cranelift-codegen/all-arch"]
lightbeam = ["wasmtime-environ/lightbeam", "wasmtime-jit/lightbeam"]
wasi-c = ["wasmtime-wasi-c"]

# [patch.crates-io]
# cranelift-wasm = { path = "../cranelift/cranelift-wasm" }
