[package]
name = "wasmtime_tools"
authors = ["The Cretonne Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmtime crate"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/sunfishcode/wasmtime"
publish = false

[[bin]]
name = "wasmtime"
path = "src/main.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cretonne-codegen = "0.13.0"
cretonne-frontend = "0.13.0"
cretonne-reader = "0.13.0"
cretonne-wasm = "0.13.0"
cretonne-native = "0.13.0"
wasmtime_runtime = { path = "lib/runtime" }
wasmtime_execute = { path = "lib/execute" }
wasmtime_obj = { path = "lib/obj" }
docopt = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
tempdir = "*"
faerie = "0.4.2"

[workspace]
