# Documentation for this configuration file can be found here
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-linux-android" },
]

# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
ignore = [
    "RUSTSEC-2020-0053", # dirs is unmaintained
]

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "CC0-1.0",
    "MIT",
    "MPL-2.0",
    "Zlib",
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "deny"
wildcards = "allow"
deny = []

# Skip some multiple-versions checks, until they can be fixed.
skip = [
    { name = "ansi_term" },
    { name = "cfg-if" },
    { name = "env_logger" },
    { name = "getrandom" },
    { name = "humantime" },
    { name = "memoffset" },
    { name = "wasmparser" },
    { name = "wast" },
]
