[package]
name = "cranelift-filetests"
authors = ["The Cranelift Project Developers"]
version = "0.60.0"
description = "Test driver and implementations of the filetest commands"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-filetests"
repository = "https://github.com/bytecodealliance/wasmtime"
publish = false
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.60.0", features = ["testing_hooks"] }
cranelift-native = { path = "../native", version = "0.60.0" }
cranelift-reader = { path = "../reader", version = "0.60.0" }
cranelift-preopt = { path = "../preopt", version = "0.60.0" }
file-per-thread-logger = "0.1.2"
filecheck = "0.5.0"
gimli = { version = "0.20.0", default-features = false, features = ["read"] }
log = "0.4.6"
memmap = "0.7.0"
num_cpus = "1.8.0"
region = "2.1.2"
byteorder = { version = "1.3.2", default-features = false }
