[package]
name = "cranelift-filetests"
authors = ["The Cranelift Project Developers"]
version = "0.0.0"
description = "Test driver and implementations of the filetest commands"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-filetests"
repository = "https://github.com/bytecodealliance/wasmtime"
publish = false
edition.workspace = true

[dependencies]
cranelift-codegen = { workspace = true, features = ["testing_hooks"] }
cranelift-frontend = { workspace = true }
cranelift-interpreter = { workspace = true }
cranelift-native = { workspace = true }
cranelift-reader = { workspace = true }
cranelift-preopt = { workspace = true }
cranelift-jit = { workspace = true, features = ["selinux-fix"] }
cranelift-module = { workspace = true }
file-per-thread-logger = "0.1.2"
filecheck = "0.5.0"
gimli = { workspace = true }
log = { workspace = true }
num_cpus = "1.8.0"
target-lexicon = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
similar = "2.1.0"
