[package]
name = "wasmtime-wast"
version = "0.1.0"
authors = ["The Wasmtime Project Developers"]
publish = false
description = "wast testing support for wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = "0.29.0"
cranelift-native = "0.29.0"
cranelift-wasm = "0.29.0"
cranelift-entity = "0.29.0"
wasmtime-jit = { path = "../wasmtime-jit" }
wasmtime-runtime = { path = "../wasmtime-runtime" }
wasmtime-environ = { path = "../wasmtime-environ" }
wabt = "0.7"
target-lexicon = "0.3.0"
failure = { version = "0.1.3", default-features = false }
failure_derive = { version = "0.1.3", default-features = false }

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/wasmtime" }
