[package]
name = "wasmtime-jit"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT-style execution for WebAsssembly code in Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { version = "0.59.0", features = ["enable-serde"] }
cranelift-entity = { version = "0.59.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.59.0", features = ["enable-serde"] }
cranelift-native = "0.59.0"
cranelift-frontend = "0.59.0"
wasmtime-environ = { path = "../environ", version = "0.12.0" }
wasmtime-runtime = { path = "../runtime", version = "0.12.0" }
wasmtime-debug = { path = "../debug", version = "0.12.0" }
wasmtime-profiling = { path = "../profiling", version = "0.12.0" }
region = "2.0.0"
thiserror = "1.0.4"
target-lexicon = { version = "0.10.0", default-features = false }
wasmparser = "0.51.2"
more-asserts = "0.2.1"
anyhow = "1.0"
cfg-if = "0.1.9"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["winnt", "impl-default"] }

[features]
lightbeam = ["wasmtime-environ/lightbeam"]

[badges]
maintenance = { status = "actively-developed" }
