[package]
name = "wasmtime-jit"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT-style execution for WebAsssembly code in Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { version = "0.50.0", features = ["enable-serde"] }
cranelift-entity = { version = "0.50.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.50.0", features = ["enable-serde"] }
cranelift-frontend = "0.50.0"
wasmtime-environ = { path = "../environ", default-features = false }
wasmtime-runtime = { path = "../runtime", default-features = false }
wasmtime-debug = { path = "../debug", default-features = false }
region = "2.0.0"
failure = { version = "0.1.3", default-features = false }
thiserror = "1.0.4"
target-lexicon = { version = "0.9.0", default-features = false }
hashbrown = { version = "0.6.0", optional = true }
wasmparser = { version = "0.39.2", default-features = false }
more-asserts = "0.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["winnt", "impl-default"] }

[features]
default = ["std"]
std = [
    "cranelift-codegen/std",
    "cranelift-wasm/std",
    "wasmtime-environ/std",
    "wasmtime-debug/std",
    "wasmtime-runtime/std",
    "wasmparser/std"
]
core = [
    "hashbrown/nightly",
    "cranelift-codegen/core",
    "cranelift-wasm/core",
    "wasmtime-environ/core",
    "wasmtime-debug/core",
    "wasmparser/core"
]
lightbeam = ["wasmtime-environ/lightbeam"]

[badges]
maintenance = { status = "actively-developed" }
