[package]
name = "wasmtime-jit"
version = "0.31.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT-style execution for WebAsssembly code in Cranelift"
documentation = "https://docs.rs/wasmtime-jit"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"

[dependencies]
wasmtime-environ = { path = "../environ", version = "=0.31.0" }
wasmtime-runtime = { path = "../runtime", version = "=0.31.0" }
region = "2.2.0"
thiserror = "1.0.4"
target-lexicon = { version = "0.12.0", default-features = false }
wasmparser = "0.81"
more-asserts = "0.2.1"
anyhow = "1.0"
cfg-if = "1.0"
log = "0.4"
gimli = { version = "0.25.0", default-features = false, features = ["std", "read"] }
object = { version = "0.27.0", default-features = false, features = ["std", "read_core", "elf"] }
serde = { version = "1.0.94", features = ["derive"] }
addr2line = { version = "0.16.0", default-features = false }
ittapi-rs = { version = "0.1.5", optional = true  }
bincode = "1.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["winnt", "impl-default"] }

[target.'cfg(target_os = "linux")'.dependencies]
rsix = { version = "0.23.0", optional = true }

[features]
jitdump = ['rsix']
vtune = ['ittapi-rs']

[badges]
maintenance = { status = "actively-developed" }
