[package]
name = "wasmtime-wast"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
description = "wast testing support for wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.19"
wasmtime = { path = "../api", version = "0.12.0", default-features = false }
wast = "11.0.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
lightbeam = ["wasmtime/lightbeam"]
