[package]
name = "wasmtime-wast"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
description = "wast testing support for wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
wasmtime-jit = { path = "../jit" }
wasmtime-runtime = { path = "../runtime" }
wasmtime-environ = { path = "../environ" }
wast = "3.0.0"
anyhow = "1.0.19"
target-lexicon = "0.9.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
lightbeam = []
