[package]
name = "wasi-common-cbindgen"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.34", features = ["full"] }
quote = "0.6.12"
proc-macro2 = "0.4.30"
