[package]
name = "cranelift-object"
version = "0.60.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with `object`"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-object"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../module", version = "0.60.0" }
object = { version = "0.18", default-features = false, features = ["write"] }
target-lexicon = "0.10"

[dependencies.cranelift-codegen]
path = "../codegen"
version = "0.60.0"
default-features = false
features = ["std"]

[badges]
maintenance = { status = "experimental" }
