[package]
name = "cranelift-object"
version = "0.59.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with `object`"
repository = "https://github.com/bytecodealliance/cranelift"
documentation = "https://cranelift.readthedocs.io/"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../cranelift-module", version = "0.59.0" }
object = { version = "0.17", default-features = false, features = ["write"] }
target-lexicon = "0.10"

[dependencies.cranelift-codegen]
path = "../cranelift-codegen"
version = "0.59.0"
default-features = false
features = ["std"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "bytecodealliance/cranelift" }
