[package]
name = "wasi-preview1-component-adapter"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wasi = { version = "0.11.0", default-features = false }
wit-bindgen = { version = "0.4.0", default-features = false, features = ["macros"] }
byte-array-literals = { workspace = true }

[build-dependencies]
wasm-encoder = "0.25"
object = { version = "0.30.0", default-features = false, features = ["archive"] }

[lib]
crate-type = ["cdylib"]

[features]
default = ["reactor"]
reactor = []
command = []
