[package]
name = "wasmtime-fuzz"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmtime-runtime = { path = "../lib/runtime" }
wasmtime-execute = { path = "../lib/execute" }
cranelift-codegen = "0.16.1"
cranelift-wasm = "0.16.1"
cranelift-native = "0.16.1"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
