[package]
name = "wasmtime-fuzz"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmtime-environ = { path = "../lib/environ" }
wasmtime-jit = { path = "../lib/jit" }
cranelift-codegen = "0.29.0"
cranelift-wasm = "0.29.0"
cranelift-native = "0.29.0"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
wasmparser = { version = "0.29.2", default-features = false }
binaryen = "0.5.0"

[features]
default = ["wasmparser/core"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"

[[bin]]
name = "instantiate"
path = "fuzz_targets/instantiate.rs"

[[bin]]
name = "instantiate_translated"
path = "fuzz_targets/instantiate_translated.rs"
