[package]
name = "wasmtime-fuzz"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmtime-environ = { path = "../wasmtime-environ" }
wasmtime-jit = { path = "../wasmtime-jit" }
cranelift-codegen = { version = "0.37.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.37.0", features = ["enable-serde"] }
cranelift-native = "0.37.0"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
wasmparser = { version = "0.32.1", default-features = false }
binaryen = "0.5.0"

[features]
default = ["wasmparser/core"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"

[[bin]]
name = "instantiate"
path = "fuzz_targets/instantiate.rs"

[[bin]]
name = "instantiate_translated"
path = "fuzz_targets/instantiate_translated.rs"
