[package]
name = "wasmtime_fuzz"
version = "0.0.1"
authors = ["The Cranelift Project Developers"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies.wasmtime_runtime]
path = "../lib/runtime"

[dependencies.wasmtime_execute]
path = "../lib/execute"

[dependencies.cranelift-codegen]
version = "0.8.0"

[dependencies.cranelift-wasm]
version = "0.8.0"

[dependencies.cranelift-native]
version = "0.8.0"

[dependencies.libfuzzer-sys]
git = "https://github.com/rust-fuzz/libfuzzer-sys.git"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
