[package]
name = "wasmtime-fuzz"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "0.2.0"
wasmtime-fuzzing = { path = "../crates/fuzzing" }
wasmtime-jit = { path = "../crates/jit" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"

[[bin]]
name = "instantiate"
path = "fuzz_targets/instantiate.rs"

[[bin]]
name = "instantiate_translated"
path = "fuzz_targets/instantiate_translated.rs"
