[package]
name = "wasmtime-fuzz"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmtime-environ = { path = "../lib/environ" }
wasmtime-execute = { path = "../lib/execute" }
cranelift-codegen = "0.24.0"
cranelift-wasm = "0.24.0"
cranelift-native = "0.24.0"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
wasmparser = { version = "0.17.2", default-features = false }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
