[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift-codegen-shared"
version = "0.51.0"
description = "For code shared between cranelift-codegen-meta and cranelift-codegen"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/cranelift"
readme = "README.md"
edition = "2018"

[dependencies]
packed_struct = "0.3"
packed_struct_codegen = "0.3"
