[package]
name = "test-programs-macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
quote = "1.0"

[build-dependencies]
# TODO: switch to release once https://github.com/bytecodealliance/wasm-tools/pull/900 has been released:
wit-component = { git = "https://github.com/bytecodealliance/wasm-tools", rev = "5ba052b9862466258f7e4d153823520ae8dabd88" }
