[package]
name = "wasmtime-wasi-crypto"
version.workspace = true
authors.workspace = true
description = "Wasmtime implementation of the wasi-crypto API"
documentation = "https://docs.rs/wasmtime-wasi-crypto"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "cryptography"]
keywords = ["webassembly", "wasm", "crypto"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
wasi-crypto = { path = "spec/implementations/hostcalls/rust", version = "0.1.5" }
wasmtime = { workspace = true }
wiggle = { workspace = true, default-features = true, features = ['wasmtime_integration'] }

[badges]
maintenance = { status = "experimental" }
