[package]
name = "cranelift-faerie"
version = "0.62.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with Faerie"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-faerie"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../module", version = "0.62.0" }
cranelift-codegen = { path = "../codegen", version = "0.62.0", default-features = false, features = ["std"] }
faerie = "0.15.0"
goblin = "0.1.0"
anyhow = "1.0"
target-lexicon = "0.10"

[badges]
maintenance = { status = "experimental" }
