[package]
name = "wasi-tokio"
version = "0.29.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"
include = ["src/**/*", "LICENSE" ]

[dependencies]
wasi-common = { path = "../", version = "0.29.0" }
wasi-cap-std-sync = { path = "../cap-std-sync", version = "0.29.0" }
wiggle = { path = "../../wiggle", version = "0.29.0" }
tokio = { version = "1.8.0", features = [ "rt", "fs", "time", "io-util", "net", "io-std", "rt-multi-thread"] }
cap-std = "0.17.0"
cap-fs-ext = "0.17.0"
cap-time-ext = "0.17.0"
fs-set-times = "0.7.0"
system-interface = { version = "0.11.0", features = ["cap_std_impls"] }
tracing = "0.1.19"
bitflags = "1.2"
anyhow = "1"
io-lifetimes = { version = "0.2.3", default-features = false }

[target.'cfg(unix)'.dependencies]
rsix = "0.18.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
lazy_static = "1.4"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.8.0", features = [ "macros" ] }
anyhow = "1"
cap-tempfile = "0.17.0"
