[package]
name = "islec"
version = "0.1.0"
authors = ["The Cranelift Project Developers"]
edition.workspace = true
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
cranelift-isle = { version = "*", path = "../isle/", features = ["miette-errors", "logging"] }
env_logger = { workspace = true }
miette = { version = "5.1.0", features = ["fancy"] }
clap = { workspace = true }
