[package]
name = "wasmtime-cranelift"
version = "0.29.0"
authors = ["The Wasmtime Project Developers"]
description = "Integration between Cranelift and Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-cranelift/"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
edition = "2018"

[dependencies]
anyhow = "1.0"
wasmtime-environ = { path = "../environ", version = "0.29.0" }
cranelift-wasm = { path = "../../cranelift/wasm", version = "0.76.0" }
cranelift-codegen = { path = "../../cranelift/codegen", version = "0.76.0" }
cranelift-frontend = { path = "../../cranelift/frontend", version = "0.76.0" }
cranelift-entity = { path = "../../cranelift/entity", version = "0.76.0" }
cranelift-native = { path = '../../cranelift/native', version = '0.76.0' }
wasmtime-debug = { path = '../debug', version = '0.29.0' }
wasmparser = "0.80.0"
target-lexicon = "0.12"
gimli = "0.25.0"
object = { version = "0.26.0", default-features = false, features = ['write'] }

[features]
all-arch = ["cranelift-codegen/all-arch"]
old-x86-backend = ["cranelift-codegen/old-x86-backend"]
