[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift-egraph"
version = "0.90.0"
description = "acyclic-egraph (aegraph) implementation for Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-egraph"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2021"

[dependencies]
cranelift-entity = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
indexmap = { version = "1.9.1" }
hashbrown = { version = "0.12.2", features = ["raw"] }
fxhash = "0.2.1"

[features]
default = []

# Enable detailed trace-level debug logging. Excluded by default to
# omit the dynamic overhead of checking the logging level.
trace-log = []
