[package]
name = "cranelift-wasm"
version = "0.89.0"
authors = ["The Cranelift Project Developers"]
description = "Translator from WebAssembly to Cranelift IR"
documentation = "https://docs.rs/cranelift-wasm"
repository = "https://github.com/bytecodealliance/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["no-std", "wasm"]
readme = "README.md"
keywords = ["webassembly", "wasm"]
edition.workspace = true

[dependencies]
wasmparser = { workspace = true }
cranelift-codegen = { workspace = true, default-features = false }
cranelift-entity = { workspace = true }
cranelift-frontend = { workspace = true, default-features = false }
wasmtime-types = { workspace = true }
hashbrown = { workspace = true, optional = true }
itertools = "0.10.0"
log = { workspace = true }
serde = { version = "1.0.94", features = ["derive"], optional = true }
smallvec = { version = "1.6.1", features = ["union"] }

[dev-dependencies]
wat = { workspace = true }
target-lexicon = { workspace = true }

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-frontend/std"]
core = ["hashbrown", "cranelift-codegen/core", "cranelift-frontend/core"]
enable-serde = ["serde"]

[badges]
maintenance = { status = "experimental" }
