# See https://dependabot.com/docs/config-file/ for a reference.
version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    allowed_updates:
    - match:
        update_type: "security"
