[package]
name = "wig"
version = "0.9.2"
authors = ["Dan Gohman <sunfish@mozilla.com>"]
description = "WebAssembly Interface Generator"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"
include = ["src/**/*", "LICENSE", "WASI"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.6"
heck = "0.3.1"
witx = "0.7.0"

[badges]
maintenance = { status = "actively-developed" }
