[package]
name = "wiggle"
version = "0.1.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkonk@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
wiggle-generate = { path = "crates/generate" }
witx = "0.8.3"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
wiggle-runtime = { path = "crates/runtime" }
wiggle-test = { path = "crates/test" }
proptest = "0.9"
