[package]
name = "wiggle"
version = "0.17.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkonk@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Runtime components of wiggle code generator"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
include = ["src/**/*", "LICENSE"]

[dependencies]
thiserror = "1"
witx = { path = "../wasi-common/WASI/tools/witx", version = "0.8.5", optional = true }
wiggle-macro = { path = "macro", version = "0.17.0" }
tracing_crate = { version = "0.1.14", optional = true, package = "tracing" }

[badges]
maintenance = { status = "actively-developed" }

[dev-dependencies]
wiggle-test = { path = "test-helpers" }
proptest = "0.9"

[features]
# The wiggle proc-macro emits some code (inside `pub mod metadata`) guarded
# by the `wiggle_metadata` feature flag. We use this feature flag so that
# users of wiggle are not forced to take a direct dependency on the `witx`
# crate unless they want it.
wiggle_metadata = ['witx', "wiggle-macro/wiggle_metadata"]
# The wiggle proc-macro emits code which may transitively depend on the
# `tracing` crate, via `wiggle::tracing`. When this feature is not enabled,
# a no-op equivelant to the tracing macros is provided instead.
tracing = [ "tracing_crate" ]

default = ["wiggle_metadata", "tracing"]
