[package]
name = "isle"
version = "0.1.0"
authors = ["Chris Fallin <chris@cfallin.org>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
log = "0.4"
env_logger = "0.8"
thiserror = "1.0"
clap = "2.33"
