[package]
name = "wasmtime-wasi"
version = "0.13.0"
authors = ["The Cranelift Project Developers"]
description = "WASI API support for Wasmtime"
documentation = "https://docs.rs/wasmtime-wasi"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0"
log = { version = "0.4.8", default-features = false }
wasi-common = { path = "../wasi-common", version = "0.13.0" }
wasmtime = { path = "../api", version = "0.13.0", default-features = false }
wasmtime-runtime = { path = "../runtime", version = "0.13.0" }
wig = { path = "../wasi-common/wig", version = "0.13.0" }
wiggle-runtime = { path = "../wiggle/crates/runtime", version = "0.13.0" }

[badges]
maintenance = { status = "actively-developed" }
