[package]
name = "wasmtime-wasi"
version = "0.23.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE", "build.rs"]
build = "build.rs"

[dependencies]
wasi-common = { path = "../wasi-common", version = "0.23.0" }
wiggle = { path = "../wiggle", default-features = false, version = "0.23.0" }
wasmtime-wiggle = { path = "../wiggle/wasmtime", default-features = false, version = "0.23.0" }
wasmtime = { path = "../wasmtime", version = "0.23.0" }
anyhow = "1.0"
