[package]
name = "wasi-common"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2"
getrandom = "0.1"
cfg-if = "0.1.9"
log = "0.4"
filetime = "0.2.7"
lazy_static = "1.4.0"
num = { version = "0.2.0", default-features = false }
wig = { path = "wig", version = "0.12.0" }
wiggle = { path = "../wiggle", default-features = false }
wiggle-runtime = { path = "../wiggle/crates/runtime" }

[target.'cfg(unix)'.dependencies]
yanix = { path = "yanix", version = "0.12.0" }

[target.'cfg(windows)'.dependencies]
winx = { path = "winx", version = "0.12.0" }
winapi = "0.3"
cpu-time = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
# Need to make the wiggle_metadata feature available to consumers of this
# crate if they want the snapshots to have metadata available.
wiggle_metadata = ["wiggle/wiggle_metadata", "wiggle-runtime/wiggle_metadata"]
