[package]
name = "wasi-common"
version = "0.15.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE", "WASI/phases", "build.rs"]

# This doesn't actually link to a native library, but it allows us to set env
# vars like `DEP_WASI_COMMON_15_*` for crates that have build scripts and depend
# on this crate, allowing other crates to use the same witx files.
links = "wasi-common-15"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2"
getrandom = "0.1"
cfg-if = "0.1.9"
log = "0.4"
filetime = "0.2.7"
lazy_static = "1.4.0"
num = { version = "0.2.0", default-features = false }
wig = { path = "wig", version = "0.15.0" }
wiggle = { path = "../wiggle", default-features = false, version = "0.15.0" }

[target.'cfg(unix)'.dependencies]
yanix = { path = "yanix", version = "0.15.0" }

[target.'cfg(windows)'.dependencies]
winx = { path = "winx", version = "0.15.0" }
winapi = "0.3"
cpu-time = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["trace_log"]
# This feature enables `log::trace` calls in syscalls shims, in effect
# emulating something like `strace`. This feature is an opt-out and hence
# enabled by default.
trace_log = []
# Need to make the wiggle_metadata feature available to consumers of this
# crate if they want the snapshots to have metadata available.
wiggle_metadata = ["wiggle/wiggle_metadata"]
